name: ci

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: s121706/keycloak:latest
      - name: scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: s121706/keycloak:latest
          annotations: true
